version: "3"
services:
  php:
    restart: always
    build:
      dockerfile: Dockerfile
      context: './php'
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - app
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app
    depends_on:
      - db           
networks:
  app:
    driver: bridge          